# Comment that will be sent if an issue is judged to be closed
comment: "This issue is closed because it does not meet our issue template. Please resubmit with the correct template."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Empire Version"
  - "Starkiller Version"
  - "OS Information (Linux flavor, Python version)"
  - "Describe the bug"
  - "To Reproduce"
  - "Expected behavior"
  - "Screenshots"
  - "Additional context"

- content:
# Example 2: feature request
  - "Is your feature request related to a problem? Please describe."
  - "Describe the solution you'd like"
  - "Describe alternatives you've considered"
  - "Additional context"
