on:
  release:
    types: [published]

name: Upload Release Asset

jobs:
  linux:
    name: Upload Release Asset Linux
    if: github.event_name == 'release' && !contains(github.ref, 'kali')
    runs-on: ubuntu-latest
    steps:
      - name: Trim release name
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)  
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build project
        run: |
          yarn
          yarn build
      - name: Bundle dist directory
        run: |
          tar -czvf starkiller-dist.tar.gz dist/
      - name: Upload Release Assets
        id: upload-release-assets
        uses: softprops/action-gh-release@v1
        with:
          # Note: the release name must match the version number in package.json.
          files: starkiller-dist.tar.gz
